### PR TITLE
Misc org update

### PR DESCRIPTION
**Pull request by dannys42**

### CODE REVIEW

**Review by mbarnach — APPROVED** [review]
👍

**Review by mbarnach — APPROVED** [review]
👍

**Comment by mbarnach** [comment]
@dannys42 I think the tests can be fixed by the PR #88

**Comment by dannys42** [comment]
@mbarnach ah cool, thanks for that.

**Comment by dannys42** [comment]
The swift-development build is failing for some reason. I added an issue (https://github.com/Kitura/SwiftyRequest/issues/89) to keep track of this.  Since the rest of the builds are succeeding, I'm pushing this through in order to continue updating packages that depend n SwiftyRequest.

**Pull request merged**
